name: Update TryHackMe badge

on:
  schedule:
    - cron: "0 5 * * *"        # kør dagligt kl. 05:00 UTC
  workflow_dispatch: {}         # mulighed for manuelt run

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # HENTER badge med p4p1-action (kræver kun THM-username)
      - name: Fetch THM badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: Ryzaxd
          output: assets/thm_badge.png  # hvor billedet gemmes i repo

      # Commit ændringer hvis filen blev opdateret
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update TryHackMe badge"
          file_pattern: assets/thm_badge.png
