name: Update TryHackMe badge

on:
  schedule:
    - cron: "0 5 * * *" 
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure assets dir exists
        run: mkdir -p assets

      - name: Fetch THM badge (static S3 image)
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: Ryzaxd             
          use_static_image: true       
          image_path: assets/thm_badge.png 
        

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update TryHackMe badge"
          file_pattern: assets/thm_badge.png
